### ISSUE TITLE
Hi! Have you ever tested SGC on PPI dataset?

### ISSUE THREAD

**Issue by Panxuran** [Tiiiger/SGC#18]
I re-implemented SGC with pytorch-geometric and test on PPI while I got only 0.45-0.5 of micro-F1 score. I wonder whether my code has something wrong or SGC is not worked on PPI?

**Comment by Tiiiger** [comment]
hi @Panxuran  personally I have not tested SGC on the PPI dataset. One thing we know though, is that SGC often doesn't work for graph classification task. Another tip for developing with SGC: because SGC is simply a linear classifier after the propagation, I encourage you to analyze the propagated features and see if there's something interesting going on.


Good luck!

**Comment by Panxuran** [comment]
Many thanks!
