### ISSUE TITLE
when I run SGC，an error occurred as follows：

### ISSUE THREAD

**Issue by yyl424525** [Tiiiger/SGC#19]
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653145446/work/aten/src/THC/THCBlas.cu:259

How can I solve this problem？

**Comment by felixgwu** [comment]
Hi @yyl424525,

I believe this is related to your pytorch installation.
Here is a similar issue. https://github.com/pytorch/pytorch/issues/17334
Because this is not related to our code, I'm closing it now.
If you have other questions regarding our code, please feel free to reach out to us again.

Best,
Felix
